### ISSUE TITLE
all form inputs that display values on the page need to be sanitized to prevent injection

### ISSUE THREAD

**Issue by broneks** [VerticalDynamics/rsvp#17]
Try using this:

http://stackoverflow.com/questions/31350737/php-remove-html-and-php-code-from-user-input
http://php.net/manual/en/function.filter-input.php

![screenshot from 2016-03-05 09-41-31](https://cloud.githubusercontent.com/assets/4494382/13548149/46d6d72a-e2b7-11e5-9d0a-8b75a738d32c.png)

**Comment by broneks** [comment]
I inserted that giant "hello" using the song artist field

**Comment by VerticalDynamics** [comment]
While we're immune to SQL injection due to all of the queries being parameterized, you've demonstrated the possibility of HTML markup tomfoolery by hacky users or, at worst, a XSS attack; both due to a lack of sanitization of user input. Despite a presumed lack of technical sophistication and malicious intent among wedding guests, it's a good idea to keep security practices in mind during the development of any project, big or small, and stay in the habit of applying them. 

Good find. I'll sanitize for HTML, CSS, and JavaScript, and conduct a mini security audit after I wrap up initial dev work. I can think of several other security vulnerabilities that this project could serve as practice for defending against. The database and the login process have zero security and the site does not authenticate over a secure connection all immediately come to mind.

**Comment by broneks** [comment]
I'm not saying that we have to go all out with https and stuff. Just saying that html & js injection is never ok, no matter how small the site. And it's easy to prevent using PHP's "filter_input()".

**Comment by VerticalDynamics** [comment]
Agree totally that users shouldn't be able to muck up the site, so to
speak, by making it do funky things like inject their own stylings. I'll do
that much at least. Using those sanitization functions is pretty
straightforward, low effort.

I was thinking aloud that if we want, we could use the site to try more
advanced security techniques like salting password hashes and such, just
for the practice. Even a login attempt counter and system configured login
attempt max would be a valuable little security addition that I've thought
about. It's good to stay security-minded for a variety of reasons. Software
projects aside, job interviewers sometimes listen for whether you're
security aware in your interview answers or code writing.

**Comment by VerticalDynamics** [comment]
User-input-accepting-fields have now been sanitized.
